### PR TITLE
fix focus/paste quirks with cells

### PR DESCRIPTION
**Pull request by jmonster**
live @ https://jd-fix-clickfocuspaste.dashboard-next.pages.dev/-est/movie-demo/source/e77094c5-4e4b-4263-a614-8e05b98f5db0/schema/public/table/Movies/

https://github.com/outerbase/dashboard.next/pull/991

### CODE REVIEW

**Review by caleb-mabry — CHANGES_REQUESTED** [review]
This improves performance, but its still not fully functional? I'm all more than happy to add this as it's an improvement but marking as Request Changes. Just say "I'll do it later" and I can approve it :) 

https://github.com/outerbase/astra-ui/assets/36182383/31dbd8b7-e103-4166-a56f-02363145fa94

**Comment by caleb-mabry** [comment]
I GOT A BETTER VIDEO! KEYS INCLUDED!!!

https://github.com/outerbase/astra-ui/assets/36182383/16044d9f-824d-4fbf-85cf-d442dfc6924d

**Review by caleb-mabry — CHANGES_REQUESTED** [review]
MUCH MUCH BETTER!!!!
The last thing I'm noticing is that when you copy/paste NULL into a cell and then try to paste another value the cell wont accept the paste :D 

https://github.com/outerbase/astra-ui/assets/36182383/8171a437-bdfe-4ff4-9766-c275775849ad

**Comment by jmonster** [comment]
@caleb-mabry could you retry latest? I made a lot of changes. I also witnessed the null thing you mentioned, but it doesn't seem to be happening anymore

it is, however, rendering the cell as blank/empty instead of saying `NULL`. I'm not really sure why thats happening but would like to bump it to another time/issue, i suspect it exists outside this PR

https://jd-fix-clickfocuspaste.dashboard-next.pages.dev/testing/postgres-testing/source/50ddadd0-8873-40f5-9f78-2347533c01de/schema/public/table/alldatatypes/

https://jd-fix-clickfocuspaste.dashboard-next.pages.dev/-est/movie-demo/source/e77094c5-4e4b-4263-a614-8e05b98f5db0/schema/public/table/Movies/

**Review by caleb-mabry — APPROVED** [review]
bonk!

**Pull request merged**
